name: update

on:
    push:
    schedule:
        - cron:  '0 * * * *'

jobs:
    update:
        env:
            extensions: curl
            key: cache-v1
            PHP_INI: date.timezone='UTC', memory_limit=-1

        strategy:
            matrix:
                os: [ 'ubuntu-latest' ]
                php: [ '8.1' ]

        runs-on: ${{ matrix.os }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.extensions }}
                    ini-values: ${{ env.PHP_INI }}
                    tools: composer:v2

            -   name: Determine composer cache directory
                run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

            -   name: Cache dependencies installed with composer
                uses: actions/cache@v2
                with:
                    path: "${{ env.COMPOSER_CACHE_DIR }}"
                    key: "php-${{ matrix.php }}-composer-${{ hashFiles('composer.lock') }}"
                    restore-keys: "php-${{ matrix.php }}-composer-"

            -   name: Install dependencies
                run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            -   name: Run update profile
                env:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                run: php update.php
